version: '3'
services:
  filebeat:
    build: ./filebeat
    depends_on:
      - logstash
  logstash:
    build: ./logstash
    depends_on:
      - elasticsearch
  elasticsearch:
    build: ./elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"